# Generated by Django 2.2.7 on 2019-11-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(choices=[('C', 'Completed'), ('R', 'Reading...'), ('CC', 'Yet to complete'), ('NS', 'Not Started')], max_length=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=60)),
                ('books', models.ManyToManyField(through='user.Read', to='book.Book')),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
