# Generated by Django 2.2.7 on 2019-11-25 18:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('published', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], max_length=2)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('R', 'Romance'), ('D', 'Drama'), ('F', 'Fiction'), ('M', 'Mystery')], max_length=7)),
            ],
        ),
    ]
